In [1]:
import pandas as pd

df_sev = pd.read_csv("freMTPL2sev.csv")
df_sev["IDpol"] = df_sev["IDpol"].astype("int64")
df_freq = pd.read_csv("freMTPL2freq.csv")
df_freq["IDpol"] = df_freq["IDpol"].astype("int64")

In [2]:
data = {
    'IDpol': [],
    'ClaimNb': [],
    'ClaimTotal': [],
    'ClaimTotalCapped': [],
    'Exposure': [],
    'Area': [],
    'VehPower': [],
    'VehAge': [],
    'DrivAge': [],
    'BonusMalus': [],
    'VehBrand': [],
    'VehGas': [],
    'Density': [],
    'Region': [],
}

In [3]:
for col, row in df_freq.iterrows():
    ID = row["IDpol"]

    data["IDpol"].append(ID)
    data["ClaimNb"].append(row["ClaimNb"])
    data["ClaimTotal"].append(df_sev.loc[df_sev["IDpol"] == ID, "ClaimAmount"].sum())
    data["ClaimTotalCapped"].append(df_sev.loc[df_sev["IDpol"] == ID, "ClaimAmount"].clip(upper=25000).sum())
    data["Exposure"].append(row["Exposure"])
    data["Area"].append(row["Area"])
    data["VehPower"].append(row["VehPower"])
    data["VehAge"].append(row["VehAge"])
    data["DrivAge"].append(row["DrivAge"])
    data["BonusMalus"].append(row["BonusMalus"])
    data["VehBrand"].append(row["VehBrand"])
    data["VehGas"].append(row["VehGas"])
    data["Density"].append(row["Density"])
    data["Region"].append(row["Region"])

In [4]:
full_pop_df = pd.DataFrame(data)
full_pop_df["Exposure"] = full_pop_df["Exposure"].clip(upper=1.0)
full_pop_df["ClaimNb"] = full_pop_df["ClaimNb"].clip(upper=11.0)
full_pop_df.describe()

,IDpol,ClaimNb,ClaimTotal,ClaimTotalCapped,Exposure,VehPower,VehAge,DrivAge,BonusMalus,Density
count,6.780130e+05,678013.000000,6.780130e+05,678013.000000,678013.000000,678013.000000,678013.000000,678013.000000,678013.000000,678013.000000
mean,2.621857e+06,0.053239,8.835998e+01,63.894112,0.528545,6.454631,7.044265,45.499122,59.761502,1792.422405
std,1.641783e+06,0.239704,5.822454e+03,648.618372,0.364081,2.050906,5.666232,14.137444,15.636658,3958.646564
min,1.000000e+00,0.000000,0.000000e+00,0.000000,0.002732,4.000000,0.000000,18.000000,50.000000,1.000000
25%,1.157951e+06,0.000000,0.000000e+00,0.000000,0.180000,5.000000,2.000000,34.000000,50.000000,92.000000
50%,2.272152e+06,0.000000,0.000000e+00,0.000000,0.490000,6.000000,6.000000,44.000000,50.000000,393.000000
75%,4.046274e+06,0.000000,0.000000e+00,0.000000,0.990000,7.000000,11.000000,55.000000,64.000000,1658.000000
max,6.114330e+06,11.000000,4.075401e+06,40600.000000,1.000000,15.000000,100.000000,100.000000,230.000000,27000.000000

In [5]:
claim_df = full_pop_df[full_pop_df["ClaimTotal"] > 0]
claim_df.describe()

,IDpol,ClaimNb,ClaimTotal,ClaimTotalCapped,Exposure,VehPower,VehAge,DrivAge,BonusMalus,Density
count,2.494400e+04,24944.000000,2.494400e+04,24944.000000,24944.000000,24944.000000,24944.000000,24944.000000,24944.000000,24944.000000
mean,2.262558e+06,1.059974,2.401749e+03,1736.731813,0.692369,6.468970,7.386225,45.139793,64.930164,1984.306166
std,1.578475e+06,0.281196,3.026475e+04,2920.689947,0.313471,2.012848,5.173621,14.658487,19.864719,4119.719566
min,1.390000e+02,1.000000,1.000000e+00,1.000000,0.002740,4.000000,0.000000,18.000000,50.000000,2.000000
25%,1.082690e+06,1.000000,7.497875e+02,749.787500,0.450000,5.000000,3.000000,34.000000,50.000000,111.000000
50%,2.130098e+06,1.000000,1.172000e+03,1172.000000,0.760000,6.000000,7.000000,45.000000,55.000000,495.000000
75%,3.178542e+06,1.000000,1.346400e+03,1346.400000,1.000000,7.000000,11.000000,54.000000,76.000000,2120.000000
max,6.113971e+06,11.000000,4.075401e+06,40600.000000,1.000000,15.000000,99.000000,99.000000,228.000000,27000.000000

In [6]:
full_pop_train = full_pop_df.sample(frac=0.8, random_state=1)
full_pop_test = full_pop_df.drop(full_pop_train.index)

claim_train = full_pop_train[full_pop_train["ClaimTotal"] > 0].copy()
claim_test = full_pop_test[full_pop_test["ClaimTotal"] > 0].copy()

In [7]:
%store full_pop_train
%store full_pop_test
%store claim_train
%store claim_test
%store full_pop_df

Stored 'full_pop_train' (DataFrame)
Stored 'full_pop_test' (DataFrame)
Stored 'claim_train' (DataFrame)
Stored 'claim_test' (DataFrame)
Stored 'full_pop_df' (DataFrame)